wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.13
    start_time: 1673017841.185764
    t:
      1:
      - 2
      - 3
      - 54
      - 55
      2:
      - 2
      - 3
      - 54
      - 55
      3:
      - 23
      - 38
      - 39
      4: 3.8.13
      5: 0.13.4
      8:
      - 1
      - 5
